runtime: python38
entrypoint: gunicorn -b :80 -w 1 main:app

instance_class: F1

handlers:
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto