runtime: python38
entrypoint: uwsgi --http-socket :80 --wsgi-file main.py --callable app --master --processes 1 --threads 2

instance_class: F1

handlers:
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto